name: Generate artifact and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate artifact for Windows
        run: |
          mkdir -p ./artifact/win/pkgs/
          touch ./artifact/win/index.html
          touch ./artifact/win/pkgs/index.html
          for a in `ls -vd ./windows/* | grep ".cmd"`; do
            echo $a
            cat $a >> ./artifact/win/index.html
            echo >> ./artifact/win/index.html
          done
          sed -i "s/::COMMIT_SHA::/${{ github.sha }}/g" ./artifact/win/index.html
          sed -i "s/::TOTAL_STEPS::/`cat ./artifact/win/index.html | grep --count 'set /a currentSteps+=1'`/g" ./artifact/win/index.html
          cat ./windows/winget-packages.txt | sed -e "s/\s.*$//g" > ./artifact/win/pkgs/index.html

      - name: Generate top page from readme
        run: |
          gh api --method POST -H "Accept: application/vnd.github+json" /markdown -f mode="gfm" -f context=$REPOSITORY -f text="$(cat ./README.md)" > ./artifact/index.html
        env:
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Debug print dir
        run: |
          ls -R ./

      - name: Debug print win
        run: |
          cat ./artifact/win/index.html

      - name: Debug print win/pkgs
        run: |
          cat ./artifact/win/pkgs/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./artifact/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
