name: Generate artifact and Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Generate artifact for Windows
              run: |
                  mkdir -p ./artifact/win/cmd
                  for file in `ls -vd ./windows/* | grep ".cmd"`; do
                    cat ${file} >> ./artifact/win/cmd/index.html
                    echo '' >> ./artifact/win/cmd/index.html
                  done
                  sed -i "s/::COMMIT_SHA::/${{ github.sha }}/g" ./artifact/win/cmd/index.html
                  sed -i "s/::TOTAL_STEPS::/`cat ./artifact/win/cmd/index.html | grep --count 'set /a currentSteps+=1'`/g" ./artifact/win/cmd/index.html
                  cp ./windows/entrypoint.ps1 ./artifact/win/index.html
                  cp ./windows/winget-packages.txt ./artifact/win/winget-packages

            - name: Generate artifact for macOS
              run: |
                  mkdir -p ./artifact/mac/
                  for file in `ls -vd ./macos/* | grep ".sh"`; do
                    cat ${file} >> ./artifact/mac/index.html
                    echo '' >> ./artifact/win/cmd/index.html
                  done
                  cp ./macos/brew-casks.txt ./artifact/mac/brew-casks
                  cp ./macos/brew-formulae.txt ./artifact/mac/brew-formulae
                  cp ./macos/mas-packages.txt ./artifact/mac/mas-packages

            - name: Generate artifact for Ubuntu
              run: |
                  mkdir -p ./artifact/ubuntu/
                  for file in `ls -vd ./ubuntu/* | grep ".sh"`; do
                    cat ${file} >> ./artifact/ubuntu/index.html
                    echo '' >> ./artifact/ubuntu/index.html
                  done
                  sed -i "s/::COMMIT_SHA::/${{ github.sha }}/g" ./artifact/ubuntu/index.html
                  cp ./ubuntu/apt-packages.txt ./artifact/ubuntu/apt-packages
                  cp ./ubuntu/flatpak-packages.txt ./artifact/ubuntu/flatpak-packages

            - name: Generate artifact for Arch
              run: |
                  mkdir -p ./artifact/arch/
                  for file in `ls -vd ./arch/* | grep ".sh"`; do
                    cat ${file} >> ./artifact/arch/index.html
                    echo '' >> ./artifact/arch/index.html
                  done
                  sed -i "s/::COMMIT_SHA::/${{ github.sha }}/g" ./artifact/arch/index.html
                  cp ./arch/packages.txt ./artifact/arch/packages

            - name: Generate top page from readme
              run: |
                  gh api --method POST -H "Accept: application/vnd.github+json" /markdown -f mode="gfm" -f context=$REPOSITORY -f text="$(cat ./README.md)" > ./artifact/index.html
              env:
                  REPOSITORY: ${{ github.repository }}
                  GITHUB_TOKEN: ${{ github.token }}

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: "./artifact/"

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
